### PR TITLE
Elisei/ds 22/create homepage bottom content

### PR DESCRIPTION
**Pull request by EliseiNicolae**

### CODE REVIEW

**Comment by stefanstax** [comment]
Are we including responsive version into this release or will it be done in the next merge?

**Review by stefanstax — CHANGES_REQUESTED** [review]
🚧 **Renamings**: 
**Homepage-sections-middle.js** -> Homepage_sections or homepageSections as well as all similar components named similarly to the above one. Maybe taking an approach of calling Header / Hp_content / Footer / Modal etc would be the best;
**Trusted by** -> StudyLionCommunities or just Communities ( Function + SCSS );
**JoinTheRevolution** -> Participation or similar synomyn 

🚧 **Bug fixes:**
TrustedBy -> key for objects is wrong. server.title is invalid; try using server.name 


Generally, all looks fine. I see that responsive is yet to be done but I assume that will be in the following pull request.

@EliseiNicolae What do you think? :)

**Comment by EliseiNicolae** [comment]
> Are we including responsive version into this release or will it be done in the next merge?

Yep, the responsive version will follow in a new PR when mobile UI will be ready. [[task](https://trello.com/c/e58pRNa5/27-responsive-mobile-waiting-ui-kate)]

**Review by stefanstax — APPROVED** [review]
All good now :)

**Pull request merged**
